### PR TITLE
practice chap 5

### PR DESCRIPTION
**Pull request by AnabelleLaurent**

### CODE REVIEW

**Comment by AnabelleLaurent** [comment]
practice chap 5

**Comment by femiguez** [comment]
Can you move these files to the appropriate folder? You are placing them under the 'notes' folder, but they belong under either Chapter 4 or Chapter 5. Thanks!

**Comment by AnabelleLaurent** [comment]
Hi,

Sorry it is not working properly, it does not update locally.
My files are attached, it takes me a while to fix that issue

Thank you
Anabelle

**Comment by femiguez** [comment]
I'll fix it, but just wanted to let you know that it is better to place the files in the folders for chapter 4 and 5

**Comment by AnabelleLaurent** [comment]
I can't see this folder on my own github and on my local copy in my laptop.

**Comment by femiguez** [comment]
That's because you need to pull from upstream. You repository is 52 commits behind master. I don't know how to do this with GitHub Desktop, but there must be something in there to keep your fork synced with 'master'. These are command line instructions about how to do this:

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Pull request merged**
